name: CI

on:
  push:
    branches: [ master ]

jobs:
  
    
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10, 12, 14]
    steps:
    - uses: actions/checkout@v2
    - name: Build with Gradle
      run: gradle build
      
    - name: show file
      run: ls build/libs/*
    
  publish:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/hacker-bills:latest
          

